### ISSUE TITLE
Converting from CentOS Stream 8 to AlmaLinux

### ISSUE THREAD

**Issue by JPGlaser** [AlmaLinux/almalinux-deploy#20] opened 2021-03-18 19:52 UTC
Currently, the script seems to not be able to convert from CentOS Stream 8 to AlmaLinux. I had hoped that for our new server that CentOS Stream was going to be somewhat compatible with our current eco-system, but it looks like it won't be. I'm glad to see the efforts being put forth here at AlmaLinux to keep open-source computing OS-s stable in the long run within the RHEL environment.

So, if I run v0.1.6 of the script, I receive the following:

```
sudo bash almalinux-deploy.sh
Check root privileges                                                 OK
Check Secure Boot disabled                                            OK
Detect centos version                                                 ERROR
Check EL is supported                                                 ERROR
```

My current distro is a clean version of CentOS Stream 8:
```
cat /etc/os-release
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
```

**Comment by titan-dn** [comment] 2021-03-19 08:22
duplicate of issue #13

**Closed by titan-dn** 2021-03-19 08:22 UTC
