### ISSUE TITLE
CentOS Linux release 8.0.1905 (Core) KVM VPS new server not updated B4 attempting the script

### ISSUE THREAD

**Issue by MrLimoAK** [AlmaLinux/almalinux-deploy#6] opened 2021-02-16 18:50 UTC
[root@server ~]# sudo bash almalinux-deploy.sh
Check root privileges                                                 OK
Check centos-8.x86_64 is supported                                    OK
Download RPM-GPG-KEY-AlmaLinux                                        OK
Import RPM-GPG-KEY-AlmaLinux to RPM DB                                OK
Download almalinux-release package                                    OK
Verify almalinux-release package                                      OK
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
        file /etc/centos-release from install of almalinux-release-8.3-2.el8.x86_64 conflicts with file from package centos-release-8.0-0.1905.0.9.el8.x86_64
        file /etc/dnf/vars/contentdir from install of almalinux-release-8.3-2.el8.x86_64 conflicts with file from package centos-release-8.0-0.1905.0.9.el8.x86_64
        file /etc/os-release from install of almalinux-release-8.3-2.el8.x86_64 conflicts with file from package centos-release-8.0-0.1905.0.9.el8.x86_64
        file /etc/redhat-release from install of almalinux-release-8.3-2.el8.x86_64 conflicts with file from package centos-release-8.0-0.1905.0.9.el8.x86_64
        file /etc/rpm/macros.dist from install of almalinux-release-8.3-2.el8.x86_64 conflicts with file from package centos-release-8.0-0.1905.0.9.el8.x86_64
        file /etc/system-release from install of almalinux-release-8.3-2.el8.x86_64 conflicts with file from package centos-release-8.0-0.1905.0.9.el8.x86_64
        file /etc/system-release-cpe from install of almalinux-release-8.3-2.el8.x86_64 conflicts with file from package centos-release-8.0-0.1905.0.9.el8.x86_64
        file /usr/lib/systemd/system-preset/90-default.preset from install of almalinux-release-8.3-2.el8.x86_64 conflicts with file from package centos-release-8.0-0.1905.0.9.el8.x86_64
        file /usr/share/doc/redhat-release from install of almalinux-release-8.3-2.el8.x86_64 conflicts with file from package centos-release-8.0-0.1905.0.9.el8.x86_64
        file /usr/share/redhat-release from install of almalinux-release-8.3-2.el8.x86_64 conflicts with file from package centos-release-8.0-0.1905.0.9.el8.x86_64

**Comment by ezamriy** [comment] 2021-02-16 19:31
Thank you for the report. It seems to be a duplicate of #1. To make it work you should first update a server to the latest CentOS version.

I did not do it automatically on purpose, because it is a bit risky operation. But I'm going to improve the script to make it check the OS version and report that it is outdated instead of crashing with conflicts.

**Closed by ezamriy** 2021-02-16 19:31 UTC
Labels: duplicate
